### ISSUE TITLE
Xbox Live Menu cause an issue

### ISSUE THREAD

**Issue by Xario123** [OfficialTeamUIX/UIX-Lite#20]
When i enter the Xbox Live menu it works.
Then i return to the main menu from the Xbox-Live submenu, the interface changes color and freezes.

For information : 
- I use an Xbox Dashboard 5960 as a base to which I add UIX Ultra Lite (pre-patched).
- I use Xemu.
- I tried with a PAL EEPROM & a NTSC EEPROM, the problem is still present.
- I share a Youtube video to illustrate the problem: https://www.youtube.com/watch?v=Z3xWzYo0Byg

**Comment by BigJx** [comment]
Thank you for the report. This Issue is resolved in v240712.
