### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by LeoABELS121** [OfficialTeamUIX/UIX-Lite#21]
The texts of menu buttons and dialog windows added with UIX are not translated when changing the dashboard language.

Will this be implemented in the future?

If so, to facilitate translation, would it be possible to provide a table of the different strings to translate?
This would allow people of different nationalities to offer a translation.

Thank you!

**Comment by BigJx** [comment]
Yes, this will be implemented in the future. Currently, the stock translations are compiled into the xboxdash.xbe.  So, will need to create a function to have it load the translations for the added content from an external file.  We will request that people of different nationalities participate in developing the translations once we get the underling code ready.

**Comment by BigJx** [comment]
Added Support for Translations. 

The xboxdashdata.185ead00-v240804 release will now load translated text from C:\xlate.xbx if it exists. The xlate.xbx file can also be found in the v0.3-Prepatched Assets. Currently does not support CJK Characters.

UPDATE: As of release v0.4 will now load translated text from C:\UIX Configs\xlate.xbx

**Comment by LeoABELS121** [comment]
It's awesome! Thank you so much! :)

**Comment by CZ2746isback** [comment]
Just adding to this based on what I got when you use an unsupported language

Japanese: Load everything just fine, but some text remain untranslated. Games will load fine.
Korean: Similar to Japanese, but some games won't work correctly.
Chinese: [Crashes the console into the service screen with error code 21. Refer to issue 44 for the reason why this occurs](https://github.com/OfficialTeamUIX/UIX-Lite/issues/44)

**Comment by BigJx** [comment]
The Chinese language will be available in the next release. Also, we were able to add support for CJK Characters to our xlate.ini.
