### ISSUE TITLE
Dash Freezes on Boot up

### ISSUE THREAD

**Issue by TheDuke72** [OfficialTeamUIX/UIX-Lite#22]
I'm having a problem where I after install the pre patch files and launch the MS Dash, It freezes on Boot up and sends me back to the softmod dash. I'm using the latest Rocky5 Softmod Extras disc for the MS Dash installation.

Xbox is 1.0 with a Seagate HDD, Not Slim Drive.

**Comment by BigJx** [comment]
The best place to get help with this issue is in #teamuix at [xbox-scene](https://discord.gg/VcdSfajQGK) on discord.

**Comment by TheDuke72** [comment]
I was told the issue could be the HDD might be dying. I had suspicions that the HDD is in fact dying, so I swapped it with a healthier Stock WD one and lock it. Now the issue is resolved.
