### ISSUE TITLE
720p display option 

### ISSUE THREAD

**Issue by Naitrate** [OfficialTeamUIX/UIX-Lite#24]
So I'm using the dashboard on a modded Xbox using a Pound HDMI cable, and I notice that the dashboard is stuck at 480 (it looks like 480i judging by the interlacing), and when I go into the network connection settings, it changes the video mode or drops out. I don't have this issue on XBMC at 720p for some reason.

Does this dashboard support 720p or 1080i? I remember hearing that the original dashboard renders at 480i, but I'm unsure if this supports anything higher.

**Comment by amak79** [comment]
I believe the MS dashboard will output at 480i even when 720p or higher is enabled. The MS dashboard can be forced to output at 480p by pressing `LT+RT+L3+R3`, so that should also work with UIX Lite.

**Comment by RibShark** [comment]
Would be nice to at least have 480p support without having to input the button combo.

**Comment by Rocky5** [comment]
> Would be nice to at least have 480p support without having to input the button combo.

It would but not everyone can run 480p and only way to do it it to force it via the XBE.

you can patch it manually with a generic 480p patch.

**Comment by Naitrate** [comment]
> It would but not everyone can run 480p and only way to do it it to force it via the XBE.
> 
> you can patch it manually with a generic 480p patch.

Got instructions on how to do this saved somewhere?

**Comment by Rocky5** [comment]
> > It would but not everyone can run 480p and only way to do it it to force it via the XBE.
> > you can patch it manually with a generic 480p patch.
> 
> Got instructions on how to do this saved somewhere?

Not sure this byte string exits is. 

`C7 46 28 20 00 00 00`
Replace with
`C7 46 28 40 00 00 00`

if it doesn’t, create a blank file named `PersistProgressiveScan` and place it in `E:\TDATA\fffe0000\` that will force 480p always, until you do the button combo to disable it or remove the file manually.
