### ISSUE TITLE
Error 21 when following your tutorial

### ISSUE THREAD

**Issue by nononymousse** [OfficialTeamUIX/UIX-Lite#3]
Hi,
i have followed your tutorial (as in #1) but i got a Error 21 when launching the dashboard. I have tried removing "unloadable false" after "archive "Music2.xip"" and "archive "Settings_Parental.xip"" from respectively "music2.xap" and "settings3.xap".

Btw i have a 1.4 Xbox, original 10Gb Seagate HDD, Rocky5 Softmod (from hotswap) and i have the kernel 5101 and the dash 5960

I can provide any files you need if you want

Hope you can help me

PS : in the requirements of this tutorial, you mention "Ideally you will be using a method with a shadowc, or a hardmod.", i'm on a softmod and i don't know what shadowc is (i have softmoded my console last week) but i see i can disable ShadowC with the Xbox Softmod Toolkit Extra Disc. I think it's a important part for this to work and i don't know if disabling it could help

**Comment by MrMilenko** [comment]
You made backups to these files correct?


On Wed, 9 Nov 2022 at 2:03 PM nononymous wrote:

Hi,
i have followed your tutorial (as in #1) but i got a Error 21 when launching the dashboard. I have tried removing "unloadable false" after "archive "Music2.xip"" and "archive "Settings_Parental.xip"" from respectively "music2.xap" and "settings3.xap".
Btw i have a 1.4 Xbox, original 10Gb Seagate HDD, Rocky5 Softmod (from hotswap) and i have the kernel 5101 and the dash 5960
I can provide any files you need if you want
Hope you can help me
PS : in the requirements of this tutorial, you mention "Ideally you will be using a method with a shadowc, or a hardmod.", i'm on a softmod and i don't know what shadowc is (i have softmoded my console last week) but i see i can disable ShadowC with the Xbox Softmod Toolkit Extra Disc. I think it's a important part for this to work and i don't know if disabling it could help

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MrMilenko/UIX-Ultra-Lite/issues/3",
"url": "https://github.com/MrMilenko/UIX-Ultra-Lite/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by nononymousse** [comment]
Yes, i have made a backup of my C and E and copy the root folder of thoses two and modified the files in this new one

**Comment by nononymousse** [comment]
i have tried doing it again today but i got the same error 21. But i noticed in WinXIP a option to Resign Dashboard, But i see here (https://consolemods.org/wiki/Xbox:Error_Codes#Error_Code_21) that i could mean that the dashboard is not correctly signed " This occurs frequently when the Xbox is unable to boot due to dashboard changes being made (i.e. an XBE hasn’t been signed correctly[...]"

I have tried signing it but winxip crash each time after selecting xboxdash.xbe. I have tried running it in admin mode, tried with my unmodified file, the Rocky5 unmodified, in a Windows XP VM (since it's from 2003), also tried on real hardware but nope, always crash. I have also tried with older version but same.

Did you encounter something like that while developing it ?

**Comment by MrMilenko** [comment]
I doubt this all together in Windows 11, you don’t need to resign anything because the hex edit removed the signature checks, and the “unloadable false” is required to be in those XAP files, I just read you said you removed them. You’re supposed to add them.Start fresh from the beginning with a new binary and set of files. If you’re running Rocky5 you’re probably using shadowC, so it shouldn’t be an issue.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/MrMilenko/UIX-Ultra-Lite/issues/3#issuecomment-1310603112",

"url": "https://github.com/MrMilenko/UIX-Ultra-Lite/issues/3#issuecomment-1310603112",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by nononymousse** [comment]
i did start fresh when i retried today, I put the dashboard from my backup to see if it was still good, it was. Then i copied the dash files and modified it.

**Comment by nononymousse** [comment]
So, i have done it again (Start from fresh) and each time i made a modification to a file, i uploaded it to the xbox and booted the dashboard to see if it work. It did work for most of them but it trow me a error 21 when i modify these sections :
- `DEF theTranslator Translator (in default.xap)

////////////////////////////////////////////////////////////////////////////

DEF theMusicInline Inline`

my modification look like this

`function StartCDPlayer()
{
    log("Should start the CD player now!");
    bGoToCDPlayer = true;
    EnableInput(false); // music.xap will re-enable it again if bGoToCDPlay is true
    GoToMusic();
}

///////////////////////////////////////////////////////////////////
DEF theMusicPlayWithSubsInline Inline
{
    visible false
    url "harddrive.xap"

    function onLoad()
    {
        theMusicPlayWithSubsInline.children[0].theMusicPlayWithSubs.GoTo();
    }
}

function GoToMusicPlayWithSubs()
{
    if (theMusicPlayWithSubsInline.visible)
        theMusicPlayWithSubsInline.children[0].theMusicPlayWithSubs.GoTo();
    else
        theMusicPlayWithSubsInline.visible = true;
}
////////////////////////////////////////////////////////////////////
{
    visible false
    url "Music2.xap"

    function onLoad()
    {
        theMusicInline.children[0].theMusicMenu.GoTo();
    }
}`

- ////// Added Functions for HDD Menu (in default.xap)

my modification look like this 
`function UnblockMemoryUnitEnumeration()
{
    theMemoryMonitor.enumerationOn = false;
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////// Added Functions for HDD Menu
////////////////////////////////////////////////////////////////////////////////////////////////////////////////



function ReturnInteger(x) // data read from xbx is read as a string - this will convert that string value to an integer
{
    var a = x;
    var b = Math.abs(a);
    if(a.charCodeAt(0) == 45)
    {
        var c = b * 2;
        b = b - c;
    }
    return b;
[...]`

Don't know if i did something wrong when modifing them (tho i feel i did wrong with the first one cuz i don't think i shouldn't remove the original part)

**Comment by MrMilenko** [comment]
Is that ‘ symbol in those files?

**Comment by nononymousse** [comment]
at each start and end of block of code, nope it's a ` and it was to mark it as code for markdown but it didn't work
otherwise, i just copy-paste from your tutorial

**Comment by nononymousse** [comment]
I have tried to put the functions one by one : for the "DEF theTranslator Translator" it still get me a error 21 but with the "Added Functions for HDD Menu", it work aside from LaunchItem(x,y), EnableCurrentAlternateViewpoint(), GetSubmenuText(),  GetConfigInfo(), GetSectionTitles(x) and GetSectionPaths(x).

**Comment by MrMilenko** [comment]
I have no idea what went wrong, or where. I'll go back and look, but I wrote this as I was doing it.

**Comment by nononymousse** [comment]
So i did it again but not from my backup but with a fresh install of Rocky5 5960 MS Dashboard, same issues at the same places tho i didn't found the hex string in the xboxdash.xbe, i did continue without doing it and it semmed fine.

I Also deleted the dashboard files and doing the update of the dash from the Halo 2 disc (that contain a 5960 dash) but same issues at the same places

Btw i think it's a minor thing but i didn't do the shortcut part since i'm still using the original HDD and don't have a F and G partition

**Comment by nononymousse** [comment]
Btw would you think it will be a good idea if you give me your dash files and put it on my console to see if it works ? And if it is, compare the files

**Comment by nononymousse** [comment]
I did i again but on Xemu and same Error 21 at the same places

**Comment by MrMilenko** [comment]
I believe I found the error in my tutorial. Markdown is breaking the syntax.

I'll edit it here soon.

**Comment by MrMilenko** [comment]
Find this:
```
DEF theTranslator Translator
```

And add this directly below it.

```
///////////////////////////////////////////////////////////////////
DEF theMusicPlayWithSubsInline Inline
{
    visible false
    url "harddrive.xap"

    function onLoad()
    {
        theMusicPlayWithSubsInline.children[0].theMusicPlayWithSubs.GoTo();
    }
}

function GoToMusicPlayWithSubs()
{
    if (theMusicPlayWithSubsInline.visible)
        theMusicPlayWithSubsInline.children[0].theMusicPlayWithSubs.GoTo();
    else
        theMusicPlayWithSubsInline.visible = true;
}
```

**Comment by nononymousse** [comment]
I applied your modification and it work for this section, i did it again from scratch (with the version on the Halo 2 disc) and now it trow me a error 21 only in the "Added Functions for HDD Menu"

**Comment by MrMilenko** [comment]
I uploaded new files and slimmed down the instructions a bit. Hope this helps.

**Comment by nononymousse** [comment]
Thank you for you work 😊
unfortunately i still have a error 21 while following your tutorial, it happend when modifing the files :
- "default.xip", when i add "default.xap"
- "mainmenu5.xip", when i add "Soundtrack_Backing.xbx" and/or Morbcellwall.xbx (like explained in #1, the file is named "orbcellwall.xbx" but i have tried to rename it to "Morbcellwall.xbx" and "morbcellwall.xbx" but still throw me a error 21)

Also i have tried putting the dash in english (it was in french and i noticed some garbage caracters where there was accents) but still the same

**Comment by MrMilenko** [comment]
Are you making the change to the other Xap files as well? Adding “unloadable false” and is the xbe hex edited?

**Comment by nononymousse** [comment]
Yup, i have downloaded the. 7z, deleted the old files and did it again from scratch following your new tutorial with fresh files

**Comment by nononymousse** [comment]
I did it again in xemu and same

**Comment by nononymousse** [comment]
Good news everyone, i finally found the problem xD
When installing the MSDash from Rocky5 extra disc, it will create a "shortcut" (1916Kb is big for just a shortcut tho imo) and i was always launching my dash through this

turn out, it give me a error 21 but when i try to launch directly xboxdash.xbe, now it run fine ^^


with one exeption, i have done the tutorial from scratch with as a base : Rocky5 files on the C drive after installing it from the Extra Disc, same with forcing a update from the Halo 2 disc and with my original files

When doing it with the Halo 2 files and with my original files, it work fine but it trow me a error 21 with Rocky5 files

the only difference i can see with Rocky5 is that the hex string you are providing are not in the xboxdash.xbe of Rocky5

But if i took the xboxdash.xbe from "Extras Disc/Softmod/dashboards/msdash/retail/5960.zip/xboxdash.xbe" and modify it like you say in your tutorial, now it work

so i don't know what they did to "broke" that (don't know if it's really broken or they did it for a reason) but it's anoying because it's less simple as "use the files from your C partition as a base, if you're not sure if it's broken or something you can install it from Rocky5 Extra Disc" and even peoples that softmoded will very probably install the MSDash from the Extra Disc since it's there

so i will investigate a bit more about but i can't promess anything

**Comment by nononymousse** [comment]
Ok i have a solution for this

the problem is that the end of your string unmodified is "[...] 75 6C 8B" while the one on the rocky5 is "[...] 90 90 8B" and it's the same as the end of your modified string

So i did a hex search without that 3 bytes at the end and i did found the same part of the code you want to change but i also did not found any other occurrence of it

so imo it's safe to edit your tutorial to remove those last 3 bytes so peoples with Rocky5 version of MSDash can install UIX Ultra Lite

**Comment by nononymousse** [comment]
Also i did a hex compare to check the difference between C:\xboxdash.xbe and E:\MSDash\default.xbe (the "shortcut" provided by Rocky5 when installing MSDash) and it's exactly the same file

i have edited that file and now i can launch the dash from it. I have also put the original Rocky5 xboxdash.xbe in C to see if it will work if i lauch the dash from E:\MSDash\default.xbe and yes so editing that "shortcut" is only needed
