### ISSUE TITLE
Play MP3 music format

### ISSUE THREAD

**Issue by LeoABELS121** [OfficialTeamUIX/UIX-Lite#43]
Hello :)

The process to transfer and make music compatible with the original Dashboard is complicated. In addition, music extracted from audio CDs is converted to WMA format, the quality of which is significantly lower than MP3. 

Are there plans to make MP3 files compatible with the UIX-Lite and to be able to play them in games like Midtown Madness 3 for example?

**Comment by nononymousse** [comment]
dunno if you had a answer but here a quick (and dirty) one : not planned cuz the dash would need to be patched as well as each games to be able to play MP3

i have heard that it exist programs to convert and transfer music to your Xbox so it can be played on it (i think it’s called Xbox Soundtrack ? i’m not sure but you can search on the web or go on XBOX Scene Discord)
