### ISSUE TITLE
Thc Orb still shows up even when turned off

### ISSUE THREAD

**Issue by Zakko64YT** [OfficialTeamUIX/UIX-Lite#5]
Even with config.xbx `Use Thc Orb=No`,
the Thc Orb still appears. I would really like the stock orb to come back.
![xboxorb](https://github.com/MrMilenko/UIX-Ultra-Lite/assets/107193204/ed9079ae-69dc-4a19-a781-4479bc9f8df3)

**Comment by kaboom36** [comment]
having the same issue here as well, tried no in all lowercase, uppercase, removing the option, leaving it blank, and a myriad of attempts with the mystery unmodified/conf file that I won't bother documenting
