### ISSUE TITLE
linux executable doesn't work

### ISSUE THREAD

**Issue by kaboom36** [OfficialTeamUIX/UIX-Lite#6]
running the linux executable gives the following output:
``````
Patched file: output/xboxdash.xbe
Make sure to copy all files from output to your Xbox. Dont forget to backup your original files
```````
but no obvious changes are made to the dashboard
windows executable works fine in wine however, unless #5 is related to that

Linux 6.5.3-200.fsync.fc37.x86_64
NAME="Nobara Linux"
VERSION="37 (KDE Plasma)"
ID=nobara
ID_LIKE="rhel centos fedora"

**Comment by nononymousse** [comment]
hi ^^
have you been able to try it again since ?

**Comment by kaboom36** [comment]
yes, I tried it just now, the patcher still does not work
I used the stock retail dashboard hosted on archive.org as I've lost the one that came with my xbox
I copied that into the unmodified folder
I then opened konsole, cd into the binary_patcher_linux directory and ran ./UIX_UL_v0_3_linux_x64
I was given the following terminal output:
`Welcome to the UIX Ultra Lite Patching Tool
Retail dashboard detected (version 5960)
Do you want to apply patches? (Y/N): y
Patch applied successfully.
`
in the output folder a modified (as checked with md5 sum) xboxdash.xbe file was placed, I copied it to my xbox and ran it using the file manager in the rocky 5 dashboard
the modified dashboard does not appear to be different from stock

**Comment by Rocky5** [comment]
> yes, I tried it just now, the patcher still does not work I used the stock retail dashboard hosted on archive.org as I've lost the one that came with my xbox I copied that into the unmodified folder I then opened konsole, cd into the binary_patcher_linux directory and ran ./UIX_UL_v0_3_linux_x64 I was given the following terminal output: `Welcome to the UIX Ultra Lite Patching Tool Retail dashboard detected (version 5960) Do you want to apply patches? (Y/N): y Patch applied successfully. ` in the output folder a modified (as checked with md5 sum) xboxdash.xbe file was placed, I copied it to my xbox and ran it using the file manager in the rocky 5 dashboard the modified dashboard does not appear to be different from stock

You did replace the xip files in the xboxdashdata.185ead00 folder also?

As all the patch does as of right now is remove the xip checks, that allow us to use unhashed and external xips. (The check may not be patched as of now, that might be next release)

**Comment by kaboom36** [comment]
ah, seems I misunderstood the purpose of the linux executable then!
I replaced the xips from the stock dash with the xips from xboxdashdata.185ead00-v240809.zip and everything is working as expected
thank you!

**Comment by Rocky5** [comment]
> ah, seems I misunderstood the purpose of the linux executable then! I replaced the xips from the stock dash with the xips from xboxdashdata.185ead00-v240809.zip and everything is working as expected thank you!

You’re welcome.
