### ISSUE TITLE
[Feature Request] Xbox Live/Insignia

### ISSUE THREAD

**Issue by Spidy123222** [OfficialTeamUIX/UIX-Lite#6]
I think for in future if there can be a Xbox live button for setting up insignia and able to download stuff from their servers. This would provide a way so that people can just fully replace the stock MS dash with UIX lite.

**Comment by Spidy123222** [comment]
Interesting insignias xb-live launcher would be a good way to add it to uix lite I think it's open source but is in development. https://github.com/insignia-live/xblunblock/

**Comment by MrMilenko** [comment]
This is being worked on, but the patch you linked is for bios's that are patched to block XBL access.

**Comment by Spidy123222** [comment]
> This is being worked on, but the patch you linked is for bios's that are patched to block XBL access.

If it is being worked on shouldn't this be open until released?
